version: '3'
services:
  minio:
    image: bitnami/minio:latest
    hostname: minio
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./01-docker-compose/minio:/data
    ports:
      - 9000:9000
      - 9001:9001

  nsq:
    image: nsqio/nsq
    restart: on-failure
    entrypoint: >
      /nsqd
    

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
      - nsq
    volumes:
      - ./02-src-data:/home/data
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/datalake;
      /usr/bin/mc policy set download myminio/datalake;
      /usr/bin/mc cp -r /home/data/ myminio/datalake/;
      /usr/bin/mc admin config set myminio notify_nsq:1 nsqd_address='nsq:4150' topic='minio'
      /usr/bin/mc mc admin service restart myminio;
      exit 0;
      "

  user-aggregator:
    container_name: user-aggregator-dt
    image: dmytrothr/user-aggregator
    restart: on-failure
    environment:
      HTTP_SERVER_PORT: ':8080'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_ROOT_USER: 'admin'
      BUCKET_SERVICE_ADDR: 'minio:9000'
      REFRESH_PERIOD_MIN: '2'
    ports:
      - 8080:8080
    depends_on:
      - minio-create-bucket
